// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACCyKYOkn6EbPMI7Ti5DpS3GfiuRPuB_A',
    appId: '1:940040443171:android:0c5bab9651c71944b9a896',
    messagingSenderId: '940040443171',
    projectId: 'fitness-tracker-app-fb-flutter',
    storageBucket: 'fitness-tracker-app-fb-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKZswVq7Us4nuMvnKdYKPutXvdQAXI8YY',
    appId: '1:940040443171:ios:be165cfd8331b12bb9a896',
    messagingSenderId: '940040443171',
    projectId: 'fitness-tracker-app-fb-flutter',
    storageBucket: 'fitness-tracker-app-fb-flutter.firebasestorage.app',
    iosClientId: '940040443171-tic4cgefspudplkmfpjadqsmsbj9414a.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitnessTrackerAppFirebase',
  );
}
